# Generated by Django 3.2.4 on 2021-06-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='isSuper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateTimeField(default=None)),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patientName', to='appointments.users')),
                ('provider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctorProviders', to='appointments.providers')),
            ],
        ),
    ]
