# Generated by Django 3.2.3 on 2021-06-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20210608_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patientName', to='appointments.users'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctorProviders', to='appointments.providers'),
        ),
    ]
